#!/usr/bin zsh

dotfiles_dir="$HOME/dotfiles"

stow_dir=("nvim" "tmux" "yabai" "skhd" "zsh")

pushd $dotfiles_dir # Move to the dotfiles dir
for dir in $stow_dir; do
    echo "=== stow $dir ==="
    stow -D "$dir"
    stow "$dir"
done
popd
